version: '3.7'

services:
  user-service:
    image: usermanager
    ports:
      - "8081:8080"
    networks:
      - microservice-network

  product-service:
    image: productmanager
    ports:
      - "8082:8080"
    deploy:
      replicas: 3
    networks:
      - microservice-network

  order-service:
    image: ordermanager
    ports:
      - "8083:8080"
    deploy:
      replicas: 3
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: overlay
